k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  clusters:
    default:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: po
  thresholds:
    cpu:
      critical: 90
      warn: 70
  ui:
    colorMode: 256
  skin: ~/.k9s/skin.yml
