import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true
[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
y = 7
x = 7
